package uet.fit.aut.execution.testdriver;

import uet.fit.aut.execution.DriverConstant;

/**
 * Generate test driver
 *
 * @author Vu + D.Anh
 */
public interface ITestDriverGeneration extends IDriverGeneration {

    String TEST_PATH_TAG = DriverConstant.TEST_PATH_FILE_TAG;
    String TEST_SCRIPTS_TAG = DriverConstant.TEST_SCRIPTS_TAG;
    String EXEC_TRACE_FILE_TAG = DriverConstant.EXEC_TRACE_FILE_TAG;
    String TEST_DRIVER_NAME = DriverConstant.TEST_DRIVER_NAME;

    // Some test cases needs to include specific headers
    // generated by automated test data generation
    String ADDITIONAL_HEADERS_TAG = DriverConstant.ADDITIONAL_HEADERS_TAG;

    String COMPOUND_TEST_CASE_SETUP = DriverConstant.COMPOUND_SET_UP;
    String COMPOUND_TEST_CASE_TEARDOWN = DriverConstant.COMPOUND_TEAR_DOWN;
    String TEST_SCRIPTS_STUB_TAG = DriverConstant.TEST_SCRIPTS_STUB_TAG;
    String INCLUDE_LIB_TAG = DriverConstant.INCLUDE_LIB_TAG;
}
